name: CI
on: pull_request

env:
  POETRY_VERSION: 1.1.6
  POETRY_HOME: ~/.poetry
  PRE_COMMIT_HOME: ~/.pre-commit

jobs:
  ci:
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.1.2
        with:
          poetry-version: ${{ env.POETRY_VERSION }}

      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v2.1.5
        with:
          path: ${{ github.workspace }}/.venv
          key: ${{ runner.os }}-poetry-${{ env.POETRY_VERSION }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Cache pre-commit hooks
        id: cache-pre-commit
        uses: actions/cache@v2.1.5
        with:
          path: ${{ env.PRE_COMMIT_HOME }}
          key: ${{ runner.os }}-pre-commit-${{ env.POETRY_VERSION }}-${{ matrix.python-version }}-${{ hashFiles('**/.pre-commit-config.yaml') }}

      - name: Install dependencies
        if: steps.cache-deps.cache-hit != 'true'
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction -E anyio

      - name: Install pre-commit hooks
        if: steps.cache-pre-commit.cache-hit != 'true'
        run: poetry run pre-commit install-hooks

      - name: Run checks
        run: poetry run pre-commit run -a

      - name: Run tests
        run: poetry run pytest -v
